In [38]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("/Users/athipongjindaphram/Documents/coffee_shop_analysis/data/coffee_shop_sales.xlsx")

In [39]:
df.sample()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
42229,42336,2023-03-13,10:57:40,2,3,Astoria,53,3.0,Tea,Brewed Chai tea,Traditional Blend Chai Lg

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

In [41]:
df.describe()

,transaction_id,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,1.438276,5.342063,47.918607,3.382219
std,43153.600016,0.542509,2.074241,17.930020,2.658723
min,1.000000,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2.000000,8.000000,60.000000,3.750000
max,149456.000000,8.000000,8.000000,87.000000,45.000000

In [42]:
print(df.isnull().sum())
print(f"Total Missing Value : {sum(df.isnull().sum())}")

transaction_id      0
transaction_date    0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64
Total Missing Value : 0

In [43]:
print(f"Rows Before Drop Duplicate : {len(df)}")

Rows Before Drop Duplicate : 149116

In [44]:
df.drop_duplicates()
print(f"Total Duplicate Rows : {df.duplicated().sum()}")
print(f"Rows After Drop Duplicate : {len(df)}")

Total Duplicate Rows : 0
Rows After Drop Duplicate : 149116

In [45]:
# Extract useful analytical sub-components
df['month_name'] = df['transaction_date'].dt.strftime('%B')
df['day_of_week'] = df['transaction_date'].dt.strftime('%A')

In [46]:
# Calculate total sales revenue for each transaction line
df['total_sales'] = df['transaction_qty'] * df['unit_price']

In [48]:
df.to_excel("/Users/athipongjindaphram/Documents/coffee_shop_analysis/data/coffee_shop_sales_cleaned.xlsx")

In [47]:
from sqlalchemy import create_engine

username = "postgres"
password = "root"
host = "localhost"
port = "5432"
database = "coffee_shop_analyze"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "coffee_sales"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data Successfully Loaded into table '{table_name}' in database '{database}'.")

Data Successfully Loaded into table 'coffee_sales' in database 'coffee_shop_analyze'.